Repository ant-design/pro-components, pull requests merged in 2020-10, with the labels that each got.

#737 fix(layout): fixedHeader=false, offsetTop should is 0
  packages/layout/src/PageContainer/index.tsx
  packages/layout/src/layout.md
  tests/table/search.test.tsx
Labels: PR: unreviewed

#738 🐛 bug: fix @ant-design/pro-utils version error
  packages/card/package.json
  packages/descriptions/package.json
  packages/field/package.json
  packages/form/package.json
  packages/layout/package.json
  packages/table/package.json
Labels: PR: unreviewed

#735 ✨ feat(form): onFinish auto close modal
  packages/form/src/BaseForm/index.tsx
  packages/form/src/demos/drawer-form.tsx
  packages/form/src/demos/light-filter-bordered.tsx
  packages/form/src/demos/light-filter-collapse.tsx
  packages/form/src/demos/light-filter.tsx
  packages/form/src/demos/modal-form.tsx
  packages/form/src/demos/query-filter-vertical.tsx
  packages/form/src/demos/query-filter.tsx
  packages/form/src/layouts/DrawerForm/index.tsx
  packages/form/src/layouts/LightFilter/index.tsx
  packages/form/src/layouts/ModalForm/index.tsx
  packages/form/src/layouts/QueryFilter/index.tsx
  packages/form/src/layouts/StepsForm/StepForm.tsx
  tests/form/drawerForm.test.tsx
  tests/form/modalForm.test.tsx
Labels: PR: unreviewed

#745 🐛 bug: fix prefixCls problem
  packages/layout/src/BasicLayout.tsx
  packages/layout/src/FooterToolbar/index.tsx
  packages/layout/src/GridContent/index.tsx
  packages/layout/src/PageContainer/index.tsx
  packages/layout/src/demos/config-provider.tsx
  packages/list/src/Item.tsx
  packages/list/src/index.tsx
  packages/table/src/component/ListToolBar/index.tsx
  packages/table/src/demos/config-provider.tsx
  tests/layout/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed, layout, table

#752 📖 docs: better doc
  docs/index.md
  docs/intro.md
  packages/form/src/form.md
  packages/layout/src/SiderMenu/index.less
  packages/layout/src/demos/_defaultProps.tsx
  packages/layout/src/layout.md
  packages/table/src/table.md
Labels: PR: unreviewed

#759 🐛 fix(loading): better loading set
  package.json
  packages/form/src/BaseForm/index.tsx
  packages/form/src/demos/query-filter.tsx
  packages/form/src/layouts/StepsForm/StepForm.tsx
  packages/form/src/layouts/StepsForm/index.tsx
Labels: PR: unreviewed

#760 Update form.md
  packages/form/src/form.md
Labels: PR: reviewed-approved

#761 ⚡️ performance: refactor option gen function
  packages/field/src/components/Select/index.tsx
  packages/table/src/demos/single.tsx
  tests/field/__snapshots__/field.test.tsx.snap
  tests/field/field.test.tsx
  tests/table/search.test.tsx
Labels: PR: unreviewed

#766 💄 style(layout): update Logo title color in light mode
  packages/layout/src/TopNavHeader/index.less
Labels: PR: reviewed-approved

#746 feat: add effective style to LightFilter when collapse
  packages/form/src/demos/light-filter-collapse.tsx
  packages/form/src/layouts/LightFilter/index.less
  packages/form/src/layouts/LightFilter/index.tsx
  tests/form/__snapshots__/demo.test.ts.snap
  tests/form/lightFilter.test.tsx
  tests/list/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#767 fix: mix layout hideInMenue bug
  packages/layout/src/Header.tsx
  tests/layout/__snapshots__/index.test.tsx.snap
  tests/layout/index.test.tsx
Labels: PR: reviewed-approved

#782 feat(card): add card direction
  packages/card/src/card.md
  packages/card/src/demos/colspan.tsx
  packages/card/src/demos/inner.tsx
  packages/card/src/index.tsx
  tests/card/__snapshots__/demo.test.ts.snap
  tests/skeleton/__snapshots__/demo.test.ts.snap
  tests/skeleton/demo.test.ts
Labels: PR: reviewed-approved

#786 📖 docs: fix api document display error problem
  packages/table/src/table.md
Labels: PR: unreviewed

#790 ✨ feat(layout): pageHeader support loading
  packages/layout/src/PageContainer/index.tsx
  packages/layout/src/layout.md
  tests/layout/__snapshots__/pageContainer.test.tsx.snap
  tests/layout/pageContainer.test.tsx
  yarn.lock
Labels: PR: unreviewed

#793 🐛 fix(layout): fix tableLayout no auto set to fixed
  packages/table/src/Table.tsx
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/index.test.tsx.snap
Labels: PR: unreviewed

#792 ✨ feat(layout): layout support menu.loading
  packages/layout/src/BasicLayout.tsx
  packages/layout/src/SiderMenu/BaseMenu.tsx
  packages/layout/src/defaultSettings.ts
  tests/layout/__snapshots__/index.test.tsx.snap
  tests/layout/index.test.tsx
Labels: PR: unreviewed

#795 🐛 fix(table): fix table ssr style
  packages/table/src/component/ToolBar/FullscreenIcon.tsx
Labels: PR: reviewed-approved

#800 fix: 修复卡片 demo
  packages/card/src/card.md
  packages/card/src/demos/colspan.tsx
  packages/card/src/demos/inner.tsx
  tests/card/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#804 📖 docs: better demos
  packages/form/src/demos/drawer-form.tsx
  packages/form/src/demos/layout-base.tsx
  packages/form/src/demos/modal-form.tsx
  packages/form/src/demos/modal-step-form.tsx
  packages/form/src/demos/multi-card-step-form.tsx
  packages/form/src/demos/steps-from.tsx
  packages/form/src/layouts/DrawerForm/index.tsx
  packages/form/src/layouts/ModalForm/index.tsx
  packages/layout/src/FooterToolbar/index.less
  packages/layout/src/SiderMenu/index.less
  packages/layout/src/demos/IconFont.tsx
  packages/layout/src/demos/Nested.tsx
  packages/layout/src/demos/complexMenu.ts
  packages/layout/src/demos/customizeMenu.tsx
  packages/layout/src/demos/dynamicMenu.tsx
  packages/layout/src/demos/hideMenu.tsx
  packages/layout/src/layout.md
  tests/form/__snapshots__/demo.test.ts.snap
  tests/layout/__snapshots__/demo.test.ts.snap
Labels: PR: reviewed-approved

#810 fix(card): card padding
  packages/card/src/style/index.less
Labels: PR: reviewed-approved

#811 refactor(layout): SettingDrawer card style
  .codecov.yml
  packages/layout/src/SettingDrawer/BlockCheckbox.tsx
  packages/layout/src/SettingDrawer/index.less
  packages/layout/src/SettingDrawer/index.tsx
  tests/layout/__snapshots__/demo.test.ts.snap
  tests/layout/__snapshots__/settingDrawer.test.tsx.snap
Labels: PR: partially-approved

#812 📖 docs: Optimize the demo
  packages/layout/src/PageContainer/index.tsx
  packages/layout/src/layout.md
  packages/table/src/Table.tsx
  packages/table/src/component/ListToolBar/index.less
  packages/table/src/demos/config-provider.tsx
  packages/table/src/demos/intl.tsx
  packages/table/src/demos/lightfilter.tsx
  packages/table/src/demos/linkage_form.tsx
  packages/table/src/demos/normal.tsx
  packages/table/src/demos/renderTable.tsx
  packages/table/src/demos/search.tsx
  packages/table/src/demos/search_backup.tsx
  packages/table/src/demos/search_option.tsx
  packages/table/src/demos/single-test.tsx
  packages/table/src/demos/single.tsx
  packages/table/src/demos/valueType.tsx
  packages/table/src/index.less
  packages/table/src/table.md
  tests/list/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/column.test.tsx.snap
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/index.test.tsx.snap
  tests/table/demo.tsx
Labels: PR: reviewed-approved

#817 fix(layout): fix PageContainer header ts definition
  packages/layout/src/PageContainer/index.tsx
  packages/table/src/table.md
Labels: PR: reviewed-approved

#821 💄 UI: optimized styleo
  package.json
  packages/form/src/components/Checkbox/index.tsx
  packages/table/src/component/ListToolBar/index.less
  packages/table/src/component/ListToolBar/index.tsx
  packages/table/src/demos/single.tsx
  tests/field/__snapshots__/field.test.tsx.snap
  tests/form/__snapshots__/demo.test.ts.snap
  tests/layout/__snapshots__/demo.test.ts.snap
  tests/layout/__snapshots__/mobile.test.tsx.snap
  tests/layout/__snapshots__/settingDrawer.test.tsx.snap
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/index.test.tsx.snap
  yarn.lock
Labels: PR: reviewed-approved

#826 💄 UI: optimized style
  package.json
  packages/form/package.json
  packages/list/package.json
  packages/skeleton/package.json
  packages/table/src/component/ListToolBar/index.less
  packages/table/src/component/ListToolBar/index.tsx
  packages/table/src/demos/lightfilter.tsx
  packages/table/src/demos/single.tsx
  tests/list/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/column.test.tsx.snap
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/index.test.tsx.snap
  yarn.lock
Labels: PR: reviewed-approved

#834 🐛 fix(table): reset will rest search value
  .github/workflows/coverage.yml
  packages/table/src/Table.tsx
  packages/table/src/component/ListToolBar/index.tsx
  packages/table/src/component/ToolBar/index.tsx
  packages/table/src/container.tsx
  packages/table/src/demos/columnsStateMap.tsx
  packages/table/src/utils.tsx
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/index.test.tsx
Labels: PR: unreviewed

#842 ✨ feat(field): fetch support cache
  package.json
  packages/field/package.json
  packages/field/src/components/Radio/index.tsx
  packages/field/src/components/Select/index.tsx
  packages/field/src/demos/base_test.tsx
  packages/field/src/index.tsx
  packages/form/src/BaseForm/index.tsx
  packages/form/src/components/Checkbox/index.tsx
  packages/table/src/Form/index.tsx
  packages/table/src/Table.tsx
  packages/table/src/defaultRender.tsx
  packages/table/src/demos/intl.tsx
  packages/table/src/demos/search.tsx
  packages/table/src/demos/search_option.tsx
  tests/field/field.test.tsx
  tests/setupTests.js
  tests/table/__snapshots__/demo.test.ts.snap
  yarn.lock
Labels: PR: unreviewed

#846 fix(card): fix collpase and inner style
  packages/card/src/demos/inner.tsx
  packages/card/src/index.tsx
  packages/card/src/style/index.less
Labels: PR: reviewed-approved

#851 fix(layout): fix pageTitle is empty error
  packages/layout/src/BasicLayout.tsx
  packages/layout/src/Header.tsx
  packages/layout/src/SiderMenu/BaseMenu.tsx
  packages/layout/src/TopNavHeader/index.tsx
  packages/layout/src/defaultSettings.ts
  packages/layout/src/getPageTitle.ts
  packages/utils/src/hooks/useDocumentTitle/index.ts
  tests/layout/getPageTitle.test.tsx
Labels: PR: unreviewed

#852 fix(table): renderFormItem should run in form init
  packages/form/src/BaseForm/index.tsx
  packages/form/src/demos/components-test.tsx
  packages/form/src/index.tsx
  packages/form/src/layouts/QueryFilter/index.tsx
  packages/table/src/Form/index.tsx
  packages/table/src/demos/linkage_form.tsx
Labels: PR: unreviewed

#854 fix(table): options or fullScreen is null, not render ConfigProvider
  packages/table/src/Table.tsx
Labels: PR: unreviewed

#855 💄 UI: better site style
  .dumi/theme/layout.less
  .dumi/theme/layout.tsx
  .umirc.js
  packages/form/src/layouts/QueryFilter/index.tsx
  packages/table/src/demos/single.tsx
  tests/form/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/column.test.tsx.snap
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/index.test.tsx.snap
Labels: PR: unreviewed

#857 fix(form): Radio and Checkbox should support children
  packages/form/src/components/Checkbox/index.tsx
  packages/form/src/components/Radio/index.tsx
  packages/form/src/demos/label-col.tsx
  tests/form/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#522 💥 feat(form): support ProFromFieldSet
  packages/field/src/components/Checkbox/index.tsx
  packages/form/src/BaseForm/LightWrapper/index.tsx
  packages/form/src/BaseForm/index.tsx
  packages/form/src/FieldContext.tsx
  packages/form/src/components/Checkbox/index.tsx
  packages/form/src/components/FieldSet/index.tsx
  packages/form/src/demos/components-other.tsx
  packages/form/src/demos/components-test.tsx
  packages/form/src/index.tsx
  packages/form/src/layouts/ProForm/index.tsx
  packages/table/src/Form/index.tsx
  packages/table/src/Table.tsx
  packages/utils/src/transformKeySubmitValue/index.ts
  tests/form/__snapshots__/demo.test.ts.snap
  tests/form/fieldSet.test.tsx
  tests/table/columnSetting.test.tsx
Labels: PR: unreviewed

#868 feat(pro-form): localize stepsform submitter buttons texts
  packages/form/src/layouts/StepsForm/index.tsx
  packages/provider/src/locale/en_US.tsx
  packages/provider/src/locale/es_ES.tsx
  packages/provider/src/locale/fr_FR.tsx
Labels: PR: reviewed-approved

#866 fix(pro-table): table 工具栏：options为false时，不显示父级节点
  packages/table/src/component/ListToolBar/index.tsx
  tests/list/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#870 test: use pull_request_target
  .github/workflows/preview.yml
Labels: PR: unreviewed

#872 🐛 fix(layout): fix current menu layout bug
  packages/layout/src/BasicLayout.tsx
  packages/layout/src/utils/useCurrentMenuLayoutProps.ts
  tests/layout/index.test.tsx
Labels: PR: unreviewed

#873 docs: 更新简介中一处语句不通顺的问题
  docs/intro.md
Labels: PR: unreviewed

#874 ✨ feat(field): support valuetype formNow
  packages/field/src/components/FromNow/index.tsx
  packages/field/src/demos/base.tsx
  packages/field/src/index.tsx
  packages/table/src/demos/valueTypeDate.tsx
  tests/field/__snapshots__/demo.test.ts.snap
  tests/field/field.test.tsx
  tests/table/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed
