Repository ant-design/pro-components, pull requests merged in 2020-11, with the labels that each got.

#875 ✨ feat(form): support ProFormCaptcha
  package.json
  packages/form/src/BaseForm/index.tsx
  packages/form/src/components/Captcha/index.tsx
  packages/form/src/components/FieldSet/index.tsx
  packages/form/src/demos/components-test.tsx
  packages/form/src/demos/login.tsx
  packages/form/src/form.md
  packages/form/src/index.tsx
  tests/form/__snapshots__/demo.test.ts.snap
  tests/form/base.test.tsx
  tests/form/fieldSet.test.tsx
  yarn.lock
Labels: PR: unreviewed

#876 🐛 fix(field): options should trigger getOptions
  packages/field/src/components/Select/index.tsx
  tests/field/field.test.tsx
Labels: PR: unreviewed

#879 🚀 refactor(list): list use antd hooks
  packages/list/src/ListView.tsx
  packages/list/src/constants.ts
  packages/list/src/demos/filter.tsx
  packages/list/src/demos/size.tsx
  packages/list/src/hooks/useLazyKVMap.ts
  packages/list/src/hooks/usePagination.ts
  packages/list/src/hooks/useSelection.tsx
  packages/list/src/index.tsx
  packages/table/src/Table.tsx
  tests/list/__snapshots__/demo.test.ts.snap
  tests/list/index.test.tsx
Labels: PR: unreviewed

#883 🐛 fix(form): support onKeyPress for Enter
  packages/form/src/BaseForm/index.tsx
  tests/form/__snapshots__/base.test.tsx.snap
  tests/form/base.test.tsx
Labels: PR: unreviewed

#889 💄 UI(layout): remove bad styles
  package.json
  packages/layout/src/SiderMenu/BaseMenu.tsx
  packages/layout/src/SiderMenu/index.less
  packages/layout/src/TopNavHeader/index.less
  packages/layout/src/demos/antd@3MenuIconFormServe.tsx
  tests/form/__snapshots__/demo.test.ts.snap
  tests/layout/__snapshots__/demo.test.ts.snap
  yarn.lock
Labels: PR: unreviewed

#892 🐛 fix(layout): fix headerTheme no work error
  packages/layout/src/GlobalHeader/index.tsx
Labels: PR: unreviewed

#893 ✨ feat(table): ListToolBar.menu support disabled
  packages/table/src/component/ListToolBar/HeaderMenu.tsx
  tests/table/listtoolbar.test.tsx
Labels: PR: unreviewed

#894 ✨ feat(form): step form onfisih support return boolean
  packages/form/src/layouts/StepsForm/index.tsx
  tests/form/stepFormTest.test.tsx
Labels: PR: unreviewed

#896 feat(pro-form): submit button text localization
  packages/form/src/layouts/StepsForm/index.tsx
  packages/provider/src/locale/en_US.tsx
  packages/provider/src/locale/es_ES.tsx
  packages/provider/src/locale/fr_FR.tsx
Labels: PR: unreviewed

#902 ⚡️ fix(form): default width is undefined
  packages/form/src/BaseForm/index.tsx
  packages/form/src/components/Checkbox/index.tsx
  packages/form/src/components/DatePicker/DatePicker.tsx
  packages/form/src/components/DatePicker/MonthPicker.tsx
  packages/form/src/components/DatePicker/QuarterPicker.tsx
  packages/form/src/components/DatePicker/WeekPicker.tsx
  packages/form/src/components/DatePicker/YearPicker.tsx
  packages/form/src/components/DateRangePicker/index.tsx
  packages/form/src/components/DateTimePicker/index.tsx
  packages/form/src/components/DateTimeRangePicker/index.tsx
  packages/form/src/components/Radio/index.tsx
  packages/form/src/components/Switch/index.tsx
  packages/form/src/demos/base.tsx
  packages/form/src/demos/components-other.tsx
  packages/form/src/demos/drawer-form.tsx
  packages/form/src/demos/layout-base.tsx
  packages/form/src/demos/modal-form.tsx
  packages/form/src/demos/modal-step-form.tsx
  packages/form/src/demos/multi-card-step-form.tsx
  packages/form/src/demos/steps-from.tsx
  packages/form/src/form.md
  packages/form/src/index.less
  packages/form/src/index.tsx
  packages/form/src/interface.d.ts
  packages/form/src/layouts/DrawerForm/index.tsx
  packages/form/src/layouts/ModalForm/index.tsx
  packages/form/src/layouts/StepsForm/index.tsx
  tests/form/__snapshots__/demo.test.ts.snap
  tests/form/drawerForm.test.tsx
  tests/form/modalForm.test.tsx
Labels: PR: unreviewed

#903 🐛 fix(form): fix transformKeySubmitValue namepath error
  packages/utils/src/transformKeySubmitValue/index.ts
Labels: PR: unreviewed

#909 chore: add ar_EG language
  packages/provider/src/index.tsx
  packages/provider/src/locale/ar_EG.tsx
  packages/table/src/demos/rtl_table.tsx
  packages/table/src/index.tsx
  packages/table/src/table.md
Labels: PR: unreviewed

#908 fix(table.md): 修改ProTable文档中参数actionRef返回的函数
  packages/table/src/table.md
Labels: PR: unreviewed

#926 fromNow 增加 Tooltip 提示
  packages/field/src/components/FromNow/index.tsx
  tests/field/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#927 🐛 fix(layout): fix the problem that openKeys does not take effect
  packages/layout/src/BasicLayout.tsx
  packages/layout/src/SiderMenu/BaseMenu.tsx
  packages/layout/src/demos/DefaultOpenAllMenu.tsx
  tests/layout/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#929 🐛 fix(field): new key gen function
  packages/field/src/components/Select/index.tsx
Labels: PR: unreviewed

#920 fix(SettingDrawer): 修复主题色 Tooltip 无提示信息问题
  packages/layout/src/SettingDrawer/ThemeColor.less
  packages/layout/src/SettingDrawer/ThemeColor.tsx
Labels: PR: unreviewed

#918 feat: 修复 ListToolBar 样式问题 & 调整部分Table 样式的demo
  .umirc.js
  package.json
  packages/form/src/layouts/LightFilter/index.less
  packages/table/src/component/Alert/index.less
  packages/table/src/component/ListToolBar/HeaderMenu.tsx
  packages/table/src/component/ListToolBar/index.less
  packages/table/src/component/ListToolBar/index.tsx
  packages/table/src/demos/ListToolBar/basic.tsx
  packages/table/src/demos/ListToolBar/custom-title.tsx
  packages/table/src/demos/ListToolBar/list.tsx
  packages/table/src/demos/ListToolBar/menu.tsx
  packages/table/src/demos/ListToolBar/multipleLine.tsx
  packages/table/src/demos/ListToolBar/no-title.tsx
  packages/table/src/demos/ListToolBar/table.tsx
  packages/table/src/demos/ListToolBar/tabs.tsx
  packages/table/src/demos/columnsStateMap.tsx
  packages/table/src/demos/lightfilter.tsx
  packages/table/src/demos/listToolBar.tsx
  packages/table/src/demos/single.tsx
  packages/table/src/index.less
  packages/table/src/table.md
  packages/utils/src/components/LabelIconTip/index.tsx
  tests/card/__snapshots__/demo.test.ts.snap
  tests/descriptions/__snapshots__/demo.test.ts.snap
  tests/list/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/column.test.tsx.snap
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/index.test.tsx.snap
  tests/table/listtoolbar.test.tsx
  yarn.lock
Labels: PR: reviewed-approved

#930 🐛 fix(table): name takes precedence over dataindex
  packages/table/src/Form/index.tsx
  packages/table/src/utils.tsx
Labels: PR: unreviewed

#933 🐛 fix(layout): pageHeaderRender should support false
  packages/layout/src/PageContainer/index.tsx
  packages/layout/src/layout.md
  tests/layout/pageHeaderWarp.test.tsx
Labels: PR: unreviewed

#936 🐛 fix(field): support some props no work error
  packages/field/src/components/Select/LightSelect/index.tsx
  tests/form/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#950 feat(field): set the useSwr option revalidateOnFocus to false
  packages/field/src/components/Select/index.tsx
Labels: PR: unreviewed

#960 🐛 fix(form): raise style priority
  packages/form/src/index.less
Labels: PR: unreviewed

#945 fix(form): fix form captcha loading error
  packages/form/src/components/Captcha/index.tsx
Labels: PR: unreviewed

#975 fix: 修复mix模式下，顶部导航渲染bug
  packages/layout/src/GlobalHeader/index.tsx
Labels: PR: unreviewed

#974 feat: LightFilter support allowClear
  packages/field/src/components/DatePicker/index.tsx
  packages/field/src/components/RangePicker/index.tsx
  packages/field/src/components/Select/LightSelect/index.tsx
  packages/field/src/components/TimePicker/index.tsx
  packages/field/src/index.tsx
  packages/form/src/BaseForm/LightWrapper/index.tsx
  packages/form/src/BaseForm/index.tsx
  packages/form/src/demos/light-filter.tsx
  packages/form/src/form.md
  packages/form/src/interface.d.ts
  packages/utils/src/components/FieldLabel/index.less
  packages/utils/src/components/FieldLabel/index.tsx
  tests/form/__snapshots__/demo.test.ts.snap
  tests/form/lightFilter.test.tsx
  tests/list/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#980 💄 UI(form): add a empty label
  packages/form/src/layouts/QueryFilter/index.tsx
  tests/form/__snapshots__/demo.test.ts.snap
  tests/form/queryFilter.test.tsx
  tests/table/__snapshots__/column.test.tsx.snap
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/index.test.tsx.snap
  tests/table/search.test.tsx
Labels: PR: unreviewed

#630 fix(field): 解决只读模式默认值为空的情况不走render的问题
  packages/field/src/index.tsx
  tests/field/field.test.tsx
Labels: PR: unreviewed

#989 feat(layout): Feat/pagecontainer ghost
  packages/layout/src/PageContainer/index.less
  packages/layout/src/demos/ghost.tsx
  packages/layout/src/layout.md
  tests/layout/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed, layout

#984 🐛 fix(table): fix render dom is 0 error
  packages/table/src/component/Alert/index.tsx
  packages/table/src/component/ListToolBar/index.tsx
  tests/list/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/column.test.tsx.snap
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/index.test.tsx.snap
Labels: PR: unreviewed

#992 feat(card): pro-card support Group and Divider
  packages/card/src/card.md
  packages/card/src/components/CardLoading/index.less
  packages/card/src/components/CardLoading/index.tsx
  packages/card/src/components/Divider/index.less
  packages/card/src/components/Divider/index.tsx
  packages/card/src/components/TabPane/index.less
  packages/card/src/components/TabPane/index.tsx
  packages/card/src/demos/divider.tsx
  packages/card/src/index.tsx
  packages/card/src/style/index.less
  tests/card/__snapshots__/demo.test.ts.snap
Labels: PR: reviewed-approved

#996 fix: missing dependency use-json-comparison
  packages/descriptions/package.json
Labels: PR: unreviewed

#1012 fix: ProFromFieldSet to ProFormFieldSet
  packages/form/src/components/FieldSet/index.tsx
  packages/form/src/demos/components-other-readonly.tsx
  packages/form/src/demos/components-other.tsx
  packages/form/src/form.md
  packages/form/src/index.tsx
  tests/form/fieldSet.test.tsx
Labels: PR: unreviewed

#1023 🐛 fix(form): fix stepForm formRef no work error
  packages/form/src/layouts/StepsForm/StepForm.tsx
Labels: PR: unreviewed

#1025 🐛 fix(table): if propsRowSelection || tableAlertRender =0 no render dom
  packages/table/src/Table.tsx
Labels: PR: unreviewed

#1024 fix(table): fix the problem that the table rendering is not timely
  packages/descriptions/src/demos/columns.tsx
  packages/field/src/field.md
  packages/form/src/components/Field/index.tsx
  packages/list/src/demos/filter.tsx
  packages/table/src/Form/index.tsx
  packages/table/src/Table.tsx
  packages/table/src/component/ColumnSetting/index.tsx
  packages/table/src/component/ToolBar/index.tsx
  packages/table/src/container.tsx
  packages/table/src/demos/ListToolBar/menu.tsx
  packages/table/src/demos/ListToolBar/multipleLine.tsx
  packages/table/src/demos/ListToolBar/no-title.tsx
  packages/table/src/demos/ListToolBar/tabs.tsx
  packages/table/src/demos/batchOption.tsx
  packages/table/src/demos/columnsStateMap.tsx
  packages/table/src/demos/config-provider.tsx
  packages/table/src/demos/crud.tsx
  packages/table/src/demos/dataSource.tsx
  packages/table/src/demos/lightfilter.tsx
  packages/table/src/demos/single.tsx
  tests/list/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/demo.tsx
  yarn.lock
Labels: PR: unreviewed

#1026 🐛 fix(field): textarea stopPropagation enter
  packages/field/src/components/TextArea/index.tsx
  tests/field/field.test.tsx
Labels: PR: unreviewed

#1028 🐛 fix(table): No more transparent formitem
  packages/form/src/BaseForm/createField.tsx
  packages/form/src/BaseForm/index.tsx
  packages/form/src/components/Captcha/index.tsx
  packages/form/src/components/Checkbox/index.tsx
  packages/form/src/components/DatePicker/DatePicker.tsx
  packages/form/src/components/DatePicker/MonthPicker.tsx
  packages/form/src/components/DatePicker/QuarterPicker.tsx
  packages/form/src/components/DatePicker/WeekPicker.tsx
  packages/form/src/components/DatePicker/YearPicker.tsx
  packages/form/src/components/DateRangePicker/index.tsx
  packages/form/src/components/DateTimePicker/index.tsx
  packages/form/src/components/DateTimeRangePicker/index.tsx
  packages/form/src/components/Digit/index.tsx
  packages/form/src/components/Field/index.tsx
  packages/form/src/components/FieldSet/index.tsx
  packages/form/src/components/Radio/index.tsx
  packages/form/src/components/Rate/index.tsx
  packages/form/src/components/Select/index.tsx
  packages/form/src/components/Slider/index.tsx
  packages/form/src/components/Switch/index.tsx
  packages/form/src/components/Text/index.tsx
  packages/form/src/components/TextArea/index.tsx
  packages/form/src/components/TimePicker/index.tsx
  packages/form/src/components/UploadButton/index.tsx
  packages/form/src/components/UploadDragger/index.tsx
  packages/table/src/Form/index.tsx
Labels: PR: unreviewed

#1031 fix(form): modal and drawer render to body
  packages/form/src/layouts/DrawerForm/index.tsx
  packages/form/src/layouts/ModalForm/index.tsx
  tests/form/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#1035 UI(card): divider style split
  packages/card/src/components/Divider/index.less
  packages/card/src/style/common.less
  packages/card/src/style/index.less
Labels: PR: unreviewed

#1037 🐛 fix(form): fix formItemProps no work error
  packages/form/src/BaseForm/createField.tsx
  packages/table/src/demos/single-test.tsx
  packages/table/src/demos/single.tsx
  tests/table/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#1039 feat(card): add direction type
  packages/card/src/index.tsx
Labels: PR: unreviewed

#1048 🐛 fix(form): do not trigger submit twice
  packages/form/src/BaseForm/index.tsx
  tests/form/__snapshots__/base.test.tsx.snap
  tests/form/__snapshots__/demo.test.ts.snap
  tests/form/upload.test.tsx
  tests/list/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/column.test.tsx.snap
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/index.test.tsx.snap
Labels: PR: unreviewed

#1054 🐛 fix(field): fix ProFormTimePicker value no moment error
  packages/field/src/components/DatePicker/index.tsx
  packages/field/src/components/TimePicker/index.tsx
Labels: PR: unreviewed

#1058 📝 docs: fix doc optional value
  packages/table/src/table.md
Labels: PR: unreviewed

#1063 fix: drawerForm&modalForm trigger 区域调整
  packages/form/src/layouts/DrawerForm/index.tsx
  packages/form/src/layouts/ModalForm/index.tsx
  tests/form/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#1069 feat: add table demos and fix form layout styles
  packages/form/src/layouts/QueryFilter/index.tsx
  packages/table/src/Table.tsx
  packages/table/src/component/ListToolBar/HeaderMenu.tsx
  packages/table/src/demos/batchOption.tsx
  packages/table/src/demos/dataSource.tsx
  packages/table/src/demos/listToolBar.tsx
  packages/table/src/demos/no-title.tsx
  packages/table/src/demos/split.tsx
  packages/table/src/table.md
  tests/form/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/column.test.tsx.snap
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/index.test.tsx.snap
  tests/table/listtoolbar.test.tsx
Labels: PR: reviewed-approved

#1074 ⚡️ feat(form): optimize query filter performance
  packages/field/src/index.tsx
  packages/form/src/BaseForm/index.tsx
  packages/form/src/layouts/QueryFilter/index.tsx
  packages/table/src/Form/index.tsx
  packages/table/src/Table.tsx
  packages/table/src/demos/linkage_form.tsx
  packages/table/src/demos/single-test.tsx
  packages/utils/src/components/LabelIconTip/index.tsx
  tests/form/__snapshots__/demo.test.ts.snap
  tests/form/stepFormTest.test.tsx
  tests/setupTests.js
  tests/table/__snapshots__/column.test.tsx.snap
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/index.test.tsx.snap
  tests/table/column.test.tsx
  tests/table/index.test.tsx
  tests/table/search.test.tsx
  tests/util.ts
Labels: PR: unreviewed

#1091 🐛 fix(table): fix filter sometime show 0 error
  packages/table/src/Table.tsx
Labels: PR: unreviewed

#1082 fix(form):fix switch readonly shows error
  packages/form/src/components/Switch/index.tsx
  packages/form/src/demos/multi-card-step-form.tsx
  packages/form/src/layouts/QueryFilter/index.tsx
  packages/form/src/layouts/StepsForm/index.tsx
  tests/form/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#994 feat(table): support editor table
  jest.config.js
  package.json
  packages/card/src/card.md
  packages/field/src/components/Code/index.tsx
  packages/field/src/index.tsx
  packages/form/src/demos/components-other-readonly.tsx
  packages/form/src/demos/components-other.tsx
  packages/form/src/form.md
  packages/list/src/demos/filter.tsx
  packages/list/src/index.tsx
  packages/table/src/EditableTable.tsx
  packages/table/src/Form/index.tsx
  packages/table/src/Table.tsx
  packages/table/src/component/Alert/index.tsx
  packages/table/src/component/ColumnSetting/index.tsx
  packages/table/src/component/InlineErrorFormItem/index.tsx
  packages/table/src/component/ToolBar/index.tsx
  packages/table/src/component/useEditable.tsx
  packages/table/src/container.tsx
  packages/table/src/defaultRender.tsx
  packages/table/src/demos/ListToolBar/menu.tsx
  packages/table/src/demos/batchOption.tsx
  packages/table/src/demos/dataSource.tsx
  packages/table/src/demos/editable-table.tsx
  packages/table/src/demos/pollinga.tsx
  packages/table/src/demos/single-test.tsx
  packages/table/src/demos/single.tsx
  packages/table/src/index.tsx
  packages/table/src/table.md
  packages/table/src/typing.ts
  packages/table/src/useFetchData.tsx
  packages/table/src/utils.tsx
  packages/utils/src/components/LabelIconTip/index.tsx
  packages/utils/src/hooks/useDebounceFn/index.ts
  packages/utils/src/typing.ts
  tests/form/__snapshots__/demo.test.ts.snap
  tests/list/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/editor-table.test.tsx.snap
  tests/table/__snapshots__/search.test.tsx.snap
  tests/table/editor-table.test.tsx
  tests/table/filter.test.tsx
  tests/table/index.test.tsx
  tests/table/search.test.tsx
  yarn.lock
Labels: PR: unreviewed

#1105 fix(table): optimize table demos and table style.
  packages/form/src/layouts/QueryFilter/Actions.tsx
  packages/form/src/layouts/QueryFilter/index.tsx
  packages/table/src/demos/ListToolBar/basic.tsx
  packages/table/src/demos/ListToolBar/menu.tsx
  packages/table/src/demos/ListToolBar/multipleLine.tsx
  packages/table/src/demos/ListToolBar/no-title.tsx
  packages/table/src/demos/ListToolBar/tabs.tsx
  packages/table/src/demos/batchOption.tsx
  packages/table/src/demos/columnsStateMap.tsx
  packages/table/src/demos/lightfilter.tsx
  packages/table/src/demos/listToolBar.tsx
  packages/table/src/demos/no-title.tsx
  packages/table/src/demos/split.less
  packages/table/src/demos/split.tsx
  packages/table/src/demos/table-nested.tsx
  packages/table/src/table.md
  packages/utils/src/components/LabelIconTip/index.less
  packages/utils/src/components/LabelIconTip/index.tsx
  tests/card/__snapshots__/demo.test.ts.snap
  tests/descriptions/__snapshots__/demo.test.ts.snap
  tests/form/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/column.test.tsx.snap
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/editor-table.test.tsx.snap
  tests/table/__snapshots__/index.test.tsx.snap
Labels: PR: unreviewed

#1121 fix(form): No longer generate redundant dom
  packages/form/src/layouts/DrawerForm/index.tsx
  packages/form/src/layouts/ModalForm/index.tsx
  tests/form/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#1129 fix(table): fix editable table show rules error
  packages/table/src/component/InlineErrorFormItem/index.tsx
  packages/table/src/demos/editable-table.tsx
  tests/table/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#1135 🐛 fix(table): fix Whitespace warning
  packages/table/src/EditableTable.tsx
  packages/table/src/demos/editable-table.tsx
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/editor-table.test.tsx.snap
Labels: PR: unreviewed

#1137 fix(form): fix setState() call inside `Field` error
  packages/field/package.json
  packages/field/src/components/Switch/index.tsx
  packages/form/src/BaseForm/index.tsx
  packages/form/src/demos/components-other-readonly.tsx
  tests/form/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#1147 fix(form): fix optionRender no has form error
  packages/form/src/BaseForm/index.tsx
  packages/form/src/layouts/QueryFilter/index.tsx
Labels: PR: unreviewed

#1143 🌎 localization: Update ar_EG.tsx
  packages/provider/src/locale/ar_EG.tsx
  tests/table/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#1138 💥 feat(card): add onClick
  packages/card/src/index.tsx
Labels: PR: unreviewed
