Repository ant-design/pro-components, pull requests merged in 2021-11, with the labels that each got.

#3921 🐛 fix(layout): breadcrumb render judge error
  packages/layout/src/components/PageContainer/demos/basic.tsx
  packages/layout/src/components/PageContainer/index.tsx
  tests/layout/__snapshots__/demo.test.ts.snap
  tests/layout/pageContainer.test.tsx
Labels: PR: unreviewed

#3895 feat(form): SchemaForm support dependency
  packages/form/src/components/SchemaForm/demos/dependency.tsx
  packages/form/src/components/SchemaForm/index.en-US.md
  packages/form/src/components/SchemaForm/index.md
  packages/form/src/components/SchemaForm/index.tsx
  tests/form/schemaForm.test.tsx
Labels: PR: unreviewed

#3943 fix(list): fix list style error
  .eslintrc.js
  package.json
  packages/form/src/demos/base.tsx
  packages/form/src/demos/formRef.tsx
  packages/form/src/demos/layout-change.tsx
  packages/form/src/demos/login-form.tsx
  packages/layout/src/demos/api.tsx
  packages/layout/src/utils/pathTools.ts
  packages/list/src/Item.tsx
  packages/list/src/index.less
  packages/table/src/components/EditableTable/demos/form-linkage.tsx
  packages/utils/src/components/InlineErrorFormItem/index.tsx
  packages/utils/src/components/LabelIconTip/index.less
  tests/form/__snapshots__/demo.test.ts.snap
  tests/list/__snapshots__/demo.test.ts.snap
  tests/list/__snapshots__/index.test.tsx.snap
  tests/list/index.test.tsx
  yarn.lock
Labels: PR: unreviewed

#3945 chore: lock swr fix mjs throw error
  packages/field/package.json
  packages/layout/package.json
  packages/utils/package.json
Labels: PR: unreviewed

#3949 feat(list): card list support rowSelection
  packages/card/src/components/Card/index.less
  packages/card/src/components/Card/index.tsx
  packages/card/src/type.ts
  packages/list/src/Item.tsx
  packages/list/src/ListView.tsx
  packages/list/src/demos/card-list.tsx
  tests/list/__snapshots__/demo.test.ts.snap
  tests/list/index.test.tsx
Labels: PR: unreviewed

#3965 🐛 fix(table): EditableTable controlled default value
  packages/table/src/components/EditableTable/index.tsx
Labels: PR: unreviewed

#3981 💥 feat(pro-descriptions): support copyable and ellipsis
  packages/descriptions/src/demos/use-data-source.tsx
  packages/descriptions/src/descriptions.en-US.md
  packages/descriptions/src/descriptions.md
  packages/descriptions/src/index.tsx
  packages/table/src/index.tsx
  tests/descriptions/__snapshots__/demo.test.ts.snap
  tests/form/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#3987 feat(field): select request 添加防抖动属性
  packages/field/src/components/Select/SearchSelect/index.tsx
  packages/field/src/components/Select/index.tsx
  packages/field/src/demos/base_test.tsx
  packages/form/src/components/FieldSet/demos/components-other.tsx
  packages/form/src/components/FieldSet/demos/search-select.tsx
  packages/form/src/components/FieldSet/index.md
  packages/form/src/components/Select/index.tsx
  packages/utils/src/hooks/useDebounceFn/index.ts
  packages/utils/src/typing.ts
  tests/demo.tsx
  tests/field/field.test.tsx
  tests/form/__snapshots__/demo.test.ts.snap
  tests/form/schemaForm.test.tsx
Labels: PR: unreviewed

#3958 fix(field): fromNow should show time
  packages/field/src/components/FromNow/index.tsx
  tests/field/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#3997 fix(table): 取消编辑行后表单未能全部重置
  packages/utils/src/useEditableArray/index.tsx
Labels: PR: reviewed-approved

#4002 chore: avoid resolve docs repeatedly
  .umirc.js
Labels: PR: unreviewed, 📕 docs

#4000 fix(table): fix editor table rowkey error
  packages/form/src/components/SchemaForm/index.tsx
  packages/list/src/ListView.tsx
  packages/table/src/Table.tsx
  packages/table/src/components/ColumnSetting/index.tsx
  packages/table/src/components/EditableTable/demos/form-item.tsx
  packages/table/src/components/EditableTable/demos/form-linkage.tsx
  packages/table/src/components/EditableTable/index.tsx
  packages/table/src/container.tsx
  packages/table/src/utils/cellRenderToFromItem.tsx
  packages/table/src/utils/columnRender.tsx
  packages/table/src/utils/genProColumnToColumn.tsx
  packages/utils/src/useEditableArray/index.tsx
  tests/table/__snapshots__/column.test.tsx.snap
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/column.test.tsx
  tests/table/editor-table.test.tsx
Labels: PR: unreviewed

#4008 feat(form): money support numberPopover
  packages/field/src/components/Money/index.tsx
  packages/field/src/demos/base_test.tsx
  packages/field/src/index.tsx
  packages/form/src/components/FieldSet/index.en-US.md
  packages/form/src/components/FieldSet/index.md
  packages/form/src/components/Money/index.tsx
  packages/form/src/demos/base.tsx
  tests/field/__snapshots__/demo.test.ts.snap
  tests/field/field.test.tsx
  tests/form/__snapshots__/demo.test.ts.snap
  tests/form/__snapshots__/proFormMoney.test.tsx.snap
  tests/form/formList.test.tsx
  tests/form/proFormMoney.test.tsx
  tests/layout/__snapshots__/footer.test.tsx.snap
  tests/layout/footer.test.tsx
  tests/layout/getPageTitle.test.tsx
Labels: PR: unreviewed

#4011 fix(form): fix proform.item no support QueryFilter error
  packages/card/src/type.ts
  packages/descriptions/src/useFetchData.tsx
  packages/field/src/components/Options/index.tsx
  packages/field/src/components/Switch/index.tsx
  packages/field/src/index.tsx
  packages/form/src/BaseForm/index.tsx
  packages/form/src/components/Captcha/index.tsx
  packages/form/src/components/DateRangePicker/index.tsx
  packages/form/src/components/Field/index.tsx
  packages/form/src/components/FormItem/index.tsx
  packages/form/src/components/QueryFilter/demos/query-filter-test.tsx
  packages/form/src/components/SchemaForm/index.tsx
  packages/form/src/components/Submitter/index.tsx
  packages/form/src/layouts/StepsForm/StepForm.tsx
  packages/layout/src/components/SettingDrawer/BlockCheckbox.tsx
  packages/layout/src/components/SettingDrawer/index.tsx
  packages/layout/src/demos/error-boundaries.tsx
  packages/layout/src/utils/utils.ts
  packages/table/src/demos/linkage_form.tsx
  packages/utils/src/components/ErrorBoundary/index.tsx
  packages/utils/src/components/InlineErrorFormItem/index.tsx
  packages/utils/src/hooks/useDebounceFn/index.ts
  packages/utils/src/hooks/useDeepCompareEffect/index.ts
  packages/utils/src/hooks/useDocumentTitle/index.ts
  packages/utils/src/pickProFormItemProps/index.tsx
  packages/utils/src/typing.ts
  tests/form/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#4013 feat(layout): support remove default title
  packages/layout/src/BasicLayout.tsx
  packages/layout/src/components/SettingDrawer/index.tsx
  packages/layout/src/components/SiderMenu/SiderMenu.tsx
  packages/layout/src/components/TopNavHeader/index.less
  packages/layout/src/defaultSettings.ts
  packages/layout/src/getPageTitle.ts
  tests/layout/__snapshots__/demo.test.ts.snap
  tests/layout/__snapshots__/pageContainer.test.tsx.snap
  tests/layout/getPageTitle.test.tsx
  tests/layout/settingDrawer.test.tsx
Labels: PR: unreviewed

#4021 🐛 fix(field): Money precision can't work
  packages/field/src/components/Money/index.tsx
Labels: PR: unreviewed

#4020 fix(layout): Improve performance
  changelog.md
  packages/form/src/demos/layout-base.tsx
  packages/layout/package.json
  packages/layout/src/BasicLayout.tsx
  packages/layout/src/components/SiderMenu/BaseMenu.tsx
  packages/layout/src/demos/AlwaysDefaultOpenAllMenu.tsx
  packages/layout/src/demos/BreadcrumbsRepeat.tsx
  packages/layout/src/demos/antd@4MenuIconFormServe.tsx
  packages/layout/src/demos/complexMenu.ts
  packages/layout/src/demos/customMenu.ts
  packages/layout/src/demos/searchMenu.tsx
  packages/layout/src/demos/top-breadcrumb.tsx
  packages/layout/src/layout.en-US.md
  packages/layout/src/layout.md
  packages/layout/src/typings.ts
  packages/layout/src/utils/getMenuData.ts
  packages/layout/src/utils/utils.ts
  tests/layout/__snapshots__/demo.test.ts.snap
  tests/layout/getPageTitle.test.tsx
  tests/layout/index.test.tsx
  yarn.lock
Labels: PR: unreviewed

#4022 fix(form): fix onchange rechange error
  packages/field/src/index.tsx
  packages/form/src/components/Field/index.tsx
  packages/layout/src/utils/getMenuData.ts
Labels: PR: unreviewed

#4027 Update README.md
  README.md
Labels: PR: unreviewed

#4033 feat(table): add card table
  packages/card/src/components/Card/index.less
  packages/form/src/demos/form-layout.tsx
  packages/table/src/demos/card-title.tsx
  packages/table/src/table.md
  tests/form/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#4037 feat(table):Reduce the use of layering and forms
  packages/form/src/BaseForm/index.tsx
  packages/form/src/components/Submitter/index.tsx
  packages/form/src/layouts/LightFilter/index.tsx
  packages/layout/src/components/SiderMenu/BaseMenu.tsx
  packages/layout/src/components/SiderMenu/index.tsx
  packages/list/src/index.less
  packages/table/src/Table.tsx
  packages/table/src/components/EditableTable/demos/form-linkage.tsx
  packages/table/src/components/EditableTable/demos/real-time-editing.tsx
  packages/table/src/components/EditableTable/index.tsx
  packages/table/src/container.tsx
  packages/table/src/utils/cellRenderToFromItem.tsx
  packages/table/src/utils/columnRender.tsx
  packages/utils/src/components/InlineErrorFormItem/index.tsx
  packages/utils/src/useEditableArray/index.tsx
  tests/setupTests.js
  tests/table/__snapshots__/editor-table.test.tsx.snap
  tests/table/editor-table.test.tsx
  tests/utils/index.test.tsx
Labels: PR: unreviewed

#4038 feat(form): support antd next
  package.json
  packages/card/src/components/Actions/index.less
  packages/card/src/components/Card/index.less
  packages/card/src/components/Divider/index.less
  packages/card/src/components/Loading/index.less
  packages/card/src/components/TabPane/index.less
  packages/descriptions/src/index.less
  packages/field/src/components/Checkbox/index.less
  packages/field/src/components/DatePicker/index.less
  packages/field/src/components/IndexColumn/index.less
  packages/field/src/components/Radio/index.less
  packages/field/src/components/Select/LightSelect/index.less
  packages/field/src/components/Select/index.less
  packages/field/src/components/Select/index.tsx
  packages/field/src/components/Status/index.less
  packages/form/src/BaseForm/LightWrapper/index.less
  packages/form/src/components/Group/index.less
  packages/form/src/components/List/index.less
  packages/form/src/components/QueryFilter/demos/search-filter.module.less
  packages/form/src/index.less
  packages/form/src/layouts/LightFilter/index.less
  packages/form/src/layouts/LoginForm/index.less
  packages/form/src/layouts/QueryFilter/index.less
  packages/form/src/layouts/StepsForm/index.less
  packages/layout/src/BasicLayout.less
  packages/layout/src/Header.less
  packages/layout/src/components/FooterToolbar/index.less
  packages/layout/src/components/GlobalFooter/index.less
  packages/layout/src/components/GlobalHeader/index.less
  packages/layout/src/components/GridContent/GridContent.less
  packages/layout/src/components/PageContainer/index.less
  packages/layout/src/components/SettingDrawer/index.less
  packages/layout/src/components/SiderMenu/index.less
  packages/layout/src/components/TopNavHeader/index.less
  packages/list/src/index.less
  packages/table/src/components/Alert/index.less
  packages/table/src/components/ColumnSetting/index.less
  packages/table/src/components/DragSortTable/index.less
  packages/table/src/components/Dropdown/index.less
  packages/table/src/components/Dropdown/index.tsx
  packages/table/src/components/Form/index.less
  packages/table/src/components/ListToolBar/index.less
  packages/table/src/components/ToolBar/index.less
  packages/table/src/index.less
  packages/utils/src/components/DropdownFooter/index.less
  packages/utils/src/components/FieldLabel/index.less
  packages/utils/src/components/FilterDropdown/index.less
  packages/utils/src/components/InlineErrorFormItem/index.less
  packages/utils/src/components/LabelIconTip/index.less
  tests/form/__snapshots__/demo.test.ts.snap
  tests/form/__snapshots__/upload.test.tsx.snap
  tests/layout/__snapshots__/demo.test.ts.snap
  tests/layout/__snapshots__/mobile.test.tsx.snap
  tests/layout/__snapshots__/settingDrawer.test.tsx.snap
  tests/list/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/column.test.tsx.snap
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/index.test.tsx.snap
  tests/table/__snapshots__/valueEnum.test.tsx.snap
  yarn.lock
Labels: PR: unreviewed

#4044 fix(form): support onVisibleChange form set
  packages/form/src/components/ModalForm/demos/drawer-form.tsx
  packages/form/src/layouts/DrawerForm/index.tsx
  packages/form/src/layouts/ModalForm/index.tsx
Labels: PR: unreviewed

#4043 fix(descriptions): fix descriptions cancel values no work error
  packages/utils/src/useEditableArray/index.tsx
Labels: PR: unreviewed

#4047 fix(table): all render cell form
  packages/table/src/utils/cellRenderToFromItem.tsx
  packages/utils/src/useEditableArray/index.tsx
Labels: PR: unreviewed

#4051 fix(form): support higher accuracy
  packages/field/src/components/Digit/index.tsx
Labels: PR: unreviewed

#4054 fix(form): fix layout="vertical" style error
  packages/form/src/layouts/QueryFilter/index.tsx
  tests/form/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#4055 feat(form): ProFormList support showItemLabel
  packages/form/src/components/Group/demos/dependency.tsx
  packages/form/src/components/Group/index.en-US.md
  packages/form/src/components/Group/index.md
  packages/form/src/components/List/index.less
  packages/form/src/components/List/index.tsx
  tests/form/__snapshots__/demo.test.ts.snap
  tests/form/formList.test.tsx
Labels: PR: unreviewed

#4058 fix(table): fix table validateFields no work error
  packages/descriptions/src/index.tsx
  packages/field/src/components/Digit/index.tsx
  packages/table/src/components/EditableTable/demos/form-item.tsx
  packages/table/src/utils/cellRenderToFromItem.tsx
  packages/utils/src/useEditableArray/index.tsx
Labels: PR: unreviewed

#4061 feat(list): support list.itemCardProps
  packages/layout/src/components/PageContainer/index.less
  packages/list/src/ListView.tsx
  packages/list/src/index.less
  packages/list/src/index.tsx
Labels: PR: unreviewed

#4062 fix(descriptions): unuse protable
  packages/descriptions/src/index.tsx
  packages/table/src/index.tsx
  packages/table/src/utils/columnRender.tsx
  packages/utils/src/genCopyable/index.tsx
  packages/utils/src/index.tsx
Labels: PR: unreviewed

#4066 fix(layout): support more token
  packages/layout/src/components/PageContainer/index.less
Labels: PR: unreviewed

#4068 fix(table): pro table support lightProps
  packages/form/src/BaseForm/createField.tsx
  packages/form/src/index.tsx
  packages/table/src/demos/lightfilter.tsx
  packages/table/src/typing.ts
  packages/utils/src/typing.ts
Labels: PR: unreviewed

#4069 还原 select request 方法参数 keyWord 为 keyWords
  packages/field/src/components/Select/index.tsx
Labels: PR: unreviewed

#4075 feat: pro-layout已支持传入props到breadcrumbProps，但文档中没有体现
  packages/layout/src/layout.md
Labels: PR: unreviewed

#4077 refactor: 💡 修改ColumnSetting中selectedKeys变量的命名错误，并修改注释
  packages/table/src/components/ColumnSetting/index.tsx
Labels: PR: unreviewed

#4074 fix(ProForm): 修复ProForm请求两次问题
  packages/field/src/components/Money/index.tsx
  packages/form/src/BaseForm/index.tsx
  packages/utils/src/hooks/useFetchData/index.tsx
Labels: PR: unreviewed

#4046 🐛 fix(field): DatePicker ellipsis can't work when mode is read
  packages/field/src/components/DatePicker/index.tsx
  packages/utils/src/genCopyable/index.tsx
  tests/descriptions/__snapshots__/demo.test.ts.snap
  tests/field/__snapshots__/demo.test.ts.snap
  tests/field/__snapshots__/field.test.tsx.snap
  tests/form/__snapshots__/demo.test.ts.snap
  tests/layout/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/__snapshots__/editor-table.test.tsx.snap
  tests/table/__snapshots__/index.test.tsx.snap
Labels: PR: unreviewed

#4097 fix(layout): no set topmenu font weight
  packages/layout/src/components/TopNavHeader/index.less
  packages/list/src/ListView.tsx
Labels: PR: unreviewed

#4119 fix:docs ProFormCascader component example
  packages/form/src/components/FieldSet/index.md
Labels: PR: unreviewed

#4117 🐛 fix(form): syncToUrl params judgment error
  packages/form/src/BaseForm/index.tsx
Labels: PR: unreviewed

#4113 🐛 fix(field): RangePicker format support funtion
  packages/field/src/components/RangePicker/index.tsx
  tests/descriptions/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#4120 feat(table): support revalidateOnFocus
  packages/field/src/components/Select/index.tsx
  packages/provider/package.json
  packages/provider/src/index.tsx
  packages/table/src/Table.tsx
  packages/table/src/components/EditableTable/index.tsx
  packages/table/src/table.en-US.md
  packages/table/src/table.md
  packages/table/src/typing.ts
  packages/table/src/useFetchData.tsx
Labels: PR: unreviewed

#4006 chore: less js size
  .fatherrc.ts
  package.json
  packages/card/package.json
  packages/descriptions/package.json
  packages/field/package.json
  packages/form/package.json
  packages/form/src/components/Cascader/index.tsx
  packages/layout/package.json
  packages/list/package.json
  packages/provider/package.json
  packages/skeleton/package.json
  packages/table/package.json
  packages/utils/package.json
  tsconfig.json
  yarn.lock
Labels: PR: unreviewed

#4124 🐛 fix(form): syncToUrl params judgment wrong order
  packages/form/src/BaseForm/index.tsx
Labels: PR: unreviewed

#4121 fix:docs: en-US docs for Layout section
  packages/layout/src/layout.en-US.md
Labels: PR: unreviewed

#4141 fix(form): fix the problem that addonBefore Required does not work when formitem is set
  packages/form/src/components/FormItem/index.tsx
  tests/form/__snapshots__/demo.test.ts.snap
Labels: PR: unreviewed

#4142 fix(#4112-ProTable中 配置了params， 通过改变params来重新请求数据时，页码没有从第一页开始): 已修复
  packages/table/src/Table.tsx
Labels: PR: unreviewed

#4151 chore: use jest new version
  .github/workflows/coverage.yml
  .github/workflows/create-release.yml
  .github/workflows/deploy.yml
  .github/workflows/fast-test.yml
  .github/workflows/webpack.yml
  jest.config.js
  package.json
  packages/layout/src/layout.en-US.md
  packages/table/src/Table.tsx
  packages/table/src/useFetchData.tsx
  packages/utils/src/useEditableArray/index.tsx
  packages/utils/src/useEditableMap/index.tsx
  packages/utils/src/useMountMergeState/index.ts
  tests/descriptions/__snapshots__/demo.test.ts.snap
  tests/form/__snapshots__/demo.test.ts.snap
  tests/jsTransformer.js
  tests/layout/__snapshots__/demo.test.ts.snap
  tests/layout/__snapshots__/index.test.tsx.snap
  tests/layout/pageContainer.test.tsx
  tests/setupTests.js
  tests/skeleton/__snapshots__/demo.test.ts.snap
  tests/skeleton/__snapshots__/skeleton.test.tsx.snap
  tests/table/__snapshots__/demo.test.ts.snap
  tests/table/polling.test.tsx
  tests/table/search.test.tsx
  yarn.lock
Labels: PR: unreviewed

#4154 📝 docs(form): QueryFilter table error
  packages/form/src/components/QueryFilter/index.md
Labels: PR: unreviewed

#4158 fix(table): if form.ignoreRules disable auto reload
  packages/table/src/Table.tsx
  packages/table/src/useFetchData.tsx
Labels: PR: unreviewed

#4161 fix(form): change numberPopoverRender render dom
  packages/field/src/components/Money/index.tsx
Labels: PR: unreviewed

#4163 fix: fix wrong comment.
  packages/table/src/components/EditableTable/demos/basic.tsx
Labels: PR: unreviewed
