Repository ant-design/pro-components, pull requests merged in 2025-08, with the labels that each got.

#9209 fix(descriptions): add style
  demos/descriptions/editable.tsx
  src/descriptions/index.tsx
  tests/descriptions/__snapshots__/editor.test.tsx.snap
  tests/descriptions/snapshot/snapshot-demos-descriptions-editable.html
  tests/layout/__snapshots__/mobile.test.tsx.snap
  tests/snapshot/snapshot-demos-descriptions-editable.html
Labels: descriptions, size:L

#9229 fix(文档): 修复文档合并展示问题
  site/components/form/Group/index.md
  site/components/group/index.md
Labels: 📕 docs, size:XS

#9216 feat(table): 表格排序与筛选相关调整修正
  site/components/table/index.md
  src/table/Table.tsx
  src/table/typing.ts
  src/table/utils/genProColumnToColumn.tsx
  src/table/utils/index.ts
  tests/table/filter.test.tsx
  tests/table/sorter.test.tsx
Labels: size:XXL

#9214 fix(form):修复Schema Form 初始化问题
  src/form/components/SchemaForm/index.tsx
Labels: form, size:XS

#9230 fix: Cascading selectors require like selector behavior
  src/field/ValueTypeToComponent.tsx
Labels: ⭕️ bug, 🧱 antd, size:XS
